default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --split-per-abi --no-tree-shake-icons"

    firebase_app_distribution(
      app: "1:628523502099:android:4a7779bbfe6080dde14de6",
      # firebase_cli_token: ENV["FIREBASE_TOKEN"],

      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk",
      testers: "mouazhariry5@gmail.com,moh.allaaadeen@gmail.com,abdullahka715@gmail.com",
      release_notes: "Fix 3 flows work correct, add cash payment methos, Edit and handle driver profile data"
    )
  end
end

# ENV["FIREBASE_TOKEN"]